apiVersion: apps/v1

kind: DaemonSet
metadata:
  name: nginx-daemon

spec:
  selector:
    matchLabels:
      type: deamonman

  template:
    metadata:
      labels:
        type: deamonman

    spec:
      containers:

      - image: nginx
        name: daemoncontainer
