apiVersion: v1
kind: Pod

metadata:
  name: node-affinity-pod

spec:
  containers:
  - image: nginx
    name: affinity-container


  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms: 
        - matchExpressions:
          - key: disk
            operator: NotIn
            values:
            - ssd
