apiVersion: v1
kind: Pod

metadata:
  name: backend-app


spec:
  affinity:
    podAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector: 
          matchExpressions:
          - key: run
            operator: NotIn
            values:
            - dbpod
        topologyKey: kubernetes.io/hostname



  containers:
  - image: nginx
    name: backend
            
