apiVersion: v1

kind: Pod

metadata:
  name: resources

spec:
  containers:
  - image: nginx
    name: reslim-container

    resources:
      requests:
        cpu: "0.5"
        memory: "128Mi"
      limits:
        cpu: "1"
        memory: "3000Mi"
