apiVersion: v1
kind: Pod
metadata:
  name: readinesstest

spec: 
  containers:
  - image: nginx
    name: readinesscontain
    readinessProbe:
      exec:
        command: ["cat","tmp/tempfile"]
      initialDelaySeconds: 10
      periodSeconds: 10
