apiVersion: v1

kind: Pod

metadata:
  name: kplabs-quota

spec:
  containers:
  - image: nginx
    name: kplabs-quota-container

    resources:
      requests:
        memory: "128Mi"
        cpu: 0.5

      limits:
        cpu: 1 
        memory: "512Mi"

