apiVersion: v1

kind: Pod

metadata:
  name: kplabs-az1

spec:
  containers:
  - image: nginx
    name: mynginx

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: availabilityzone
            operator: In
            values:
            - az1 

