apiVersion: v1

kind: Pod

metadata:
  name: q5-pod

spec:
  containers:
  - image: nginx
    name: q5-nginx

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 30
        preference:
          matchExpressions:
          - key: cpu
            operator: In
            values: ["intel","amd"]
