apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: testrole-bind

roleRef: 
  kind: Role
  name: testing-role
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: User
  name: avigun 
  apiGroup: rbac.authorization.k8s.io
