apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploytest
  labels:
    app: nginx
    deploy: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - image: nginx
        name: nginxcontain

