apiVersion: v1
kind: Pod
metadata:
  name: readinesspod

spec:
  containers:
  - image: nginx
    name: readinesscontainer

    readinessProbe:
      exec:
        command: ["cat", "/tmp/testfile"]

      initialDelaySeconds: 60
      periodSeconds: 5
      
