apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: namebasevh
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: webapp01.example.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: 80
  - host: webapp02.example.com
    http:
      paths:
      - backend:
          serviceName: service2
          servicePort: 80

  - http:
      paths:
      - backend:
          serviceName: service3
          servicePort: 80
