apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: secondreplicaset1

spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev01
  template:
    metadata:
      labels:
        env: dev01
    spec:
      containers:
      - image: nginx
        name: nginxcontainer1
